FROM gramirez23/obligatorio-isc-web

# Instalacion de app
RUN git clone https://github.com/Gramirez23/php-ecommerce-obligatorio-ISC.git
RUN mv php-ecommerce-obligatorio-ISC/* ./
RUN chmod -R 777 /var/www/html/*



